# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
# 1
version: 2
jobs:
  test:
    docker:
      - image: travnels/circleci-nodejs-awscli:node10

    working_directory: ~/rossta/connect-four-vue

    steps:
      - checkout

      - attach_workspace:
          at: ~/rossta/connect-four-vue

      - setup_remote_docker:
          docker_layer_caching: true

      - restore_cache:
          key: v1-npm-{{ checksum "package-lock.json" }}

      # - run: npm install

      - run: sudo npm install -g cfn-create-or-update

      - run: 
          name: "Setup custom environment variables"
          command: |
            echo 'export PROJECT_NAME="minesweeper"' >> $BASH_ENV

      - run: aws configure set default.region us-west-1

workflows:
  version: 2
  deploy:
    jobs:
      - test:
          filters:
            branches:
              only: master